FROM --platform=$BUILDPLATFORM golang:1.23.4-alpine AS builder

ARG TARGETOS
ARG TARGETARCH

WORKDIR /app
COPY go.mod .
COPY main.go .

RUN <<EOF
go mod tidy
GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -o generate-npc
EOF


FROM busybox
#FROM scratch
WORKDIR /app
COPY --from=builder /app/generate-npc .
COPY instructions /app/instructions

#CMD ["./generate-npc"]
