services:

  ollama-service:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    restart: always
  
  bot-dragon-service:
    build: 
      context: .
      dockerfile: Dockerfile.bot
      platforms: 
        - linux/arm64    
    command: ./bot-npc ./data/character-dragon-lorinirion.json
    environment:
      - OLLAMA_HOST=http://ollama-service:11434
      - LLM_CHAT=qwen2.5:0.5b
    ports:
      - 5051:8080
    volumes:
      - ./data:/app/data
    depends_on:
      ollama-service:
        condition: service_started


  bot-hobbit-service:
    build: 
      context: .
      dockerfile: Dockerfile.bot
      platforms: 
        - linux/arm64    
    command: ./bot-npc ./data/character-hobbit-tin-rya.json
    environment:
      - OLLAMA_HOST=http://ollama-service:11434
      - LLM_CHAT=qwen2.5:0.5b
    ports:
      - 5052:8080
    volumes:
      - ./data:/app/data
    depends_on:
      ollama-service:
        condition: service_started

  bot-werewolf-service:
    build: 
      context: .
      dockerfile: Dockerfile.bot
      platforms: 
        - linux/arm64    
    command: ./bot-npc ./data/character-werewolf-thornwood.json
    environment:
      - OLLAMA_HOST=http://ollama-service:11434
      - LLM_CHAT=qwen2.5:0.5b
    ports:
      - 5053:8080
    volumes:
      - ./data:/app/data
    depends_on:
      ollama-service:
        condition: service_started

  bot-dwarf-service:
    build: 
      context: .
      dockerfile: Dockerfile.bot
      platforms: 
        - linux/arm64    
    command: ./bot-npc ./data/character-dwarf-thorin_oak-speech.json
    environment:
      - OLLAMA_HOST=http://ollama-service:11434
      - LLM_CHAT=qwen2.5:0.5b
    ports:
      - 5054:8080
    volumes:
      - ./data:/app/data
    depends_on:
      ollama-service:
        condition: service_started